// apps/tanstack-start/src/components/ui/skeleton.tsx
import { cn } from '@/lib/utils';

interface SkeletonProps extends React.ComponentProps<'div'> {
	delayed?: boolean;
}

function Skeleton({ className, delayed = false, ...props }: SkeletonProps) {
	return (
		<div
			data-slot="skeleton"
			className={cn('rounded-none', delayed ? 'skeleton-delayed' : 'skeleton-warm', className)}
			{...props}
		/>
	);
}

export { Skeleton };

// examples/sveltekit/src/lib/components/ui/skeleton/skeleton.svelte
<script lang="ts">
	import { cn, type WithElementRef, type WithoutChildren } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		delayed = false,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLDivElement>>> & { delayed?: boolean } = $props();
</script>

<div
	bind:this={ref}
	data-slot="skeleton"
	class={cn(
		"rounded-none",
		delayed ? "skeleton-delayed" : "skeleton-warm",
		className
	)}
	{...restProps}
></div>
